// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SantiagoConectaIA.DAL.Models;

public partial class AbonoApartado
{
    public int IIdAbonoApartado { get; set; }

    public int IIdApartado { get; set; }

    public decimal MAbono { get; set; }

    public DateTime DtFechaAbono { get; set; }

    public virtual Apartado IIdApartadoNavigation { get; set; }
}