// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SantiagoConectaIA.DAL.Models;

public partial class ApartadoDetalle
{
    public int IIdApartadoDetalle { get; set; }

    public int IIdApartado { get; set; }

    public int IIdArticulo { get; set; }

    public int ICantidad { get; set; }

    public decimal MPrecioFinal { get; set; }

    public virtual Apartado IIdApartadoNavigation { get; set; }

    public virtual Articulo IIdArticuloNavigation { get; set; }
}