// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SantiagoConectaIA.DAL.Models;

public partial class Apartado
{
    public int IIdApartado { get; set; }

    public string NvchNombreCliente { get; set; }

    public DateTime DtFechaApartado { get; set; }

    public decimal MTotal { get; set; }

    public bool BPagado { get; set; }

    public string NvchComentario { get; set; }

    public virtual ICollection<AbonoApartado> AbonoApartados { get; set; } = new List<AbonoApartado>();

    public virtual ICollection<ApartadoDetalle> ApartadoDetalles { get; set; } = new List<ApartadoDetalle>();
}