// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SantiagoConectaIA.DAL.Models;

public partial class ApiCallLog
{
    public int IIdApiCallLog { get; set; }

    public string VchEndpoint { get; set; }

    public string VchRequestMethod { get; set; }

    public DateTime DtRequestTimestamp { get; set; }

    public string NvchRequestBody { get; set; }

    public DateTime DtResponseTimestamp { get; set; }

    public string NvchResponseBody { get; set; }

    public bool BIsSuccess { get; set; }

    public int IDurationMs { get; set; }

    public string VchHost { get; set; }
}