// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SantiagoConectaIA.DAL.Models;

public partial class Articulo
{
    public int IIdArticulo { get; set; }

    public string NvchNombre { get; set; }

    public string VchCodigo { get; set; }

    public decimal MPrecioCompra { get; set; }

    public decimal MPrecioVenta { get; set; }

    public int? IIdProveedor { get; set; }

    public string NvchDescripcion { get; set; }

    public bool BActivo { get; set; }

    public virtual ICollection<ApartadoDetalle> ApartadoDetalles { get; set; } = new List<ApartadoDetalle>();

    public virtual Proveedor IIdProveedorNavigation { get; set; }

    public virtual ICollection<Inventario> Inventarios { get; set; } = new List<Inventario>();

    public virtual ICollection<PedidoDetalle> PedidoDetalles { get; set; } = new List<PedidoDetalle>();

    public virtual ICollection<Ventum> Venta { get; set; } = new List<Ventum>();
}