// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SantiagoConectaIA.DAL.Models;

public partial class BuzonCiudadano
{
    public int IIdReporte { get; set; }

    public string NvchNombreCiudadano { get; set; }

    public string NvchEmail { get; set; }

    public string NvchTelefono { get; set; }

    public string NvchCategoria { get; set; }

    public string NvchDescripcion { get; set; }

    public DateTime DtFechaReporte { get; set; }

    public string NvchThreadId { get; set; }
}