// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SantiagoConectaIA.DAL.Models;

public partial class Catalogo
{
    public int IdCatalogo { get; set; }

    public int IdGrupo { get; set; }

    public string Descripcion { get; set; }

    public string Valor { get; set; }

    public virtual Grupo IdGrupoNavigation { get; set; }

    public virtual ICollection<NoticiaMetadato> NoticiaMetadatos { get; set; } = new List<NoticiaMetadato>();
}