// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SantiagoConectaIA.DAL.Models;

public partial class CategoriaNoticium
{
    public int IIdCategoria { get; set; }

    public string VchNombre { get; set; }

    public string VchColorHex { get; set; }

    public bool BActivo { get; set; }

    public virtual ICollection<Noticia> Noticia { get; set; } = new List<Noticia>();
}