// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SantiagoConectaIA.DAL.Models;

public partial class Chat
{
    public int IIdChat { get; set; }

    public DateTime DtFechaCreacion { get; set; }

    public string NvchNombre { get; set; }

    public bool BActivo { get; set; }

    public string NvchThreadId { get; set; }

    public int IIdProyecto { get; set; }

    public virtual Proyecto IIdProyectoNavigation { get; set; }

    public virtual ICollection<Mensaje> Mensajes { get; set; } = new List<Mensaje>();
}