// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SantiagoConectaIA.DAL.Models
{
    public partial class DTApartadoDetalle
    {
        public int? iIdApartadoDetalle { get; set; }
        public int? iIdApartado { get; set; }
        public int? iIdArticulo { get; set; }
        public int? iCantidad { get; set; }
        [Column("mPrecioFinal", TypeName = "money")]
        public decimal? mPrecioFinal { get; set; }
    }
}
