// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SantiagoConectaIA.DAL.Models
{
    public partial class DTParameterType
    {
        public int? iParameter { get; set; }
        [StringLength(255)]
        public string vchParameter { get; set; }
        public DateTime? dtParameter { get; set; }
        [Column("mParametr", TypeName = "money")]
        public decimal? mParametr { get; set; }
        public short? smParameter { get; set; }
        public bool? bParameter { get; set; }
    }
}
