// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace SantiagoConectaIA.DAL.Models;

public partial class EngramaContext : DbContext
{
    public EngramaContext(DbContextOptions<EngramaContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AbonoApartado> AbonoApartados { get; set; }

    public virtual DbSet<Apartado> Apartados { get; set; }

    public virtual DbSet<ApartadoDetalle> ApartadoDetalles { get; set; }

    public virtual DbSet<ApiCallLog> ApiCallLogs { get; set; }

    public virtual DbSet<Articulo> Articulos { get; set; }

    public virtual DbSet<BuzonCiudadano> BuzonCiudadanos { get; set; }

    public virtual DbSet<Catalogo> Catalogos { get; set; }

    public virtual DbSet<CategoriaNoticium> CategoriaNoticia { get; set; }

    public virtual DbSet<Chat> Chats { get; set; }

    public virtual DbSet<Documento> Documentos { get; set; }

    public virtual DbSet<Fase> Fases { get; set; }

    public virtual DbSet<Funcionalidad> Funcionalidads { get; set; }

    public virtual DbSet<Grupo> Grupos { get; set; }

    public virtual DbSet<HistorialConsultum> HistorialConsulta { get; set; }

    public virtual DbSet<Inventario> Inventarios { get; set; }

    public virtual DbSet<Mensaje> Mensajes { get; set; }

    public virtual DbSet<Modulo> Modulos { get; set; }

    public virtual DbSet<Noticia> Noticias { get; set; }

    public virtual DbSet<NoticiaFila> NoticiaFilas { get; set; }

    public virtual DbSet<NoticiaMetadato> NoticiaMetadatos { get; set; }

    public virtual DbSet<NoticiasImagene> NoticiasImagenes { get; set; }

    public virtual DbSet<Oficina> Oficinas { get; set; }

    public virtual DbSet<OficinaTramite> OficinaTramites { get; set; }

    public virtual DbSet<Paso> Pasos { get; set; }

    public virtual DbSet<Pedido> Pedidos { get; set; }

    public virtual DbSet<PedidoDetalle> PedidoDetalles { get; set; }

    public virtual DbSet<PlanTrabajo> PlanTrabajos { get; set; }

    public virtual DbSet<Proveedor> Proveedors { get; set; }

    public virtual DbSet<Proyecto> Proyectos { get; set; }

    public virtual DbSet<Requisito> Requisitos { get; set; }

    public virtual DbSet<TestTable> TestTables { get; set; }

    public virtual DbSet<TipoDato> TipoDatos { get; set; }

    public virtual DbSet<Tramite> Tramites { get; set; }

    public virtual DbSet<TramitePaso> TramitePasos { get; set; }

    public virtual DbSet<Usuario> Usuarios { get; set; }

    public virtual DbSet<Ventum> Venta { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<AbonoApartado>(entity =>
        {
            entity.HasKey(e => e.IIdAbonoApartado).HasName("PK__AbonoApa__5ABBC5BD501B501B");

            entity.ToTable("AbonoApartado");

            entity.HasIndex(e => e.IIdApartado, "IX_AbonoApartado_iIdApartado");

            entity.Property(e => e.IIdAbonoApartado).HasColumnName("iIdAbonoApartado");
            entity.Property(e => e.DtFechaAbono)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("dtFechaAbono");
            entity.Property(e => e.IIdApartado).HasColumnName("iIdApartado");
            entity.Property(e => e.MAbono)
                .HasColumnType("money")
                .HasColumnName("mAbono");

            entity.HasOne(d => d.IIdApartadoNavigation).WithMany(p => p.AbonoApartados)
                .HasForeignKey(d => d.IIdApartado)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AbonoApartado_Apartado");
        });

        modelBuilder.Entity<Apartado>(entity =>
        {
            entity.HasKey(e => e.IIdApartado).HasName("PK__Apartado__33520BFEE70758AE");

            entity.ToTable("Apartado");

            entity.Property(e => e.IIdApartado).HasColumnName("iIdApartado");
            entity.Property(e => e.BPagado).HasColumnName("bPagado");
            entity.Property(e => e.DtFechaApartado)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("dtFechaApartado");
            entity.Property(e => e.MTotal)
                .HasColumnType("money")
                .HasColumnName("mTotal");
            entity.Property(e => e.NvchComentario)
                .IsRequired()
                .HasMaxLength(1000)
                .HasColumnName("nvchComentario");
            entity.Property(e => e.NvchNombreCliente)
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnName("nvchNombreCliente");
        });

        modelBuilder.Entity<ApartadoDetalle>(entity =>
        {
            entity.HasKey(e => e.IIdApartadoDetalle).HasName("PK__Apartado__B3FD55B44A4B544A");

            entity.ToTable("ApartadoDetalle");

            entity.HasIndex(e => e.IIdApartado, "IX_ApartadoDetalle_iIdApartado");

            entity.Property(e => e.IIdApartadoDetalle).HasColumnName("iIdApartadoDetalle");
            entity.Property(e => e.ICantidad).HasColumnName("iCantidad");
            entity.Property(e => e.IIdApartado).HasColumnName("iIdApartado");
            entity.Property(e => e.IIdArticulo).HasColumnName("iIdArticulo");
            entity.Property(e => e.MPrecioFinal)
                .HasColumnType("money")
                .HasColumnName("mPrecioFinal");

            entity.HasOne(d => d.IIdApartadoNavigation).WithMany(p => p.ApartadoDetalles)
                .HasForeignKey(d => d.IIdApartado)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ApartadoDetalle_Apartado");

            entity.HasOne(d => d.IIdArticuloNavigation).WithMany(p => p.ApartadoDetalles)
                .HasForeignKey(d => d.IIdArticulo)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ApartadoDetalle_Articulo");
        });

        modelBuilder.Entity<ApiCallLog>(entity =>
        {
            entity.HasKey(e => e.IIdApiCallLog).HasName("PK__ApiCallL__D013B5BB790AD616");

            entity.Property(e => e.IIdApiCallLog).HasColumnName("iIdApiCallLog");
            entity.Property(e => e.BIsSuccess).HasColumnName("bIsSuccess");
            entity.Property(e => e.DtRequestTimestamp)
                .HasColumnType("datetime")
                .HasColumnName("dtRequestTimestamp");
            entity.Property(e => e.DtResponseTimestamp)
                .HasColumnType("datetime")
                .HasColumnName("dtResponseTimestamp");
            entity.Property(e => e.IDurationMs).HasColumnName("iDurationMs");
            entity.Property(e => e.NvchRequestBody).HasColumnName("nvchRequestBody");
            entity.Property(e => e.NvchResponseBody).HasColumnName("nvchResponseBody");
            entity.Property(e => e.VchEndpoint)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("vchEndpoint");
            entity.Property(e => e.VchHost)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("vchHost");
            entity.Property(e => e.VchRequestMethod)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("vchRequestMethod");
        });

        modelBuilder.Entity<Articulo>(entity =>
        {
            entity.HasKey(e => e.IIdArticulo).HasName("PK__Articulo__91ABCCFB199F8F7A");

            entity.ToTable("Articulo");

            entity.Property(e => e.IIdArticulo).HasColumnName("iIdArticulo");
            entity.Property(e => e.BActivo)
                .HasDefaultValue(true)
                .HasColumnName("bActivo");
            entity.Property(e => e.IIdProveedor).HasColumnName("iIdProveedor");
            entity.Property(e => e.MPrecioCompra)
                .HasColumnType("money")
                .HasColumnName("mPrecioCompra");
            entity.Property(e => e.MPrecioVenta)
                .HasColumnType("money")
                .HasColumnName("mPrecioVenta");
            entity.Property(e => e.NvchDescripcion)
                .HasMaxLength(1000)
                .HasColumnName("nvchDescripcion");
            entity.Property(e => e.NvchNombre)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("nvchNombre");
            entity.Property(e => e.VchCodigo)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("vchCodigo");

            entity.HasOne(d => d.IIdProveedorNavigation).WithMany(p => p.Articulos)
                .HasForeignKey(d => d.IIdProveedor)
                .HasConstraintName("FK_Articulo_iIdProveedor");
        });

        modelBuilder.Entity<BuzonCiudadano>(entity =>
        {
            entity.HasKey(e => e.IIdReporte).HasName("PK__BuzonCiu__A3D36F46F8579FB7");

            entity.ToTable("BuzonCiudadano");

            entity.Property(e => e.IIdReporte).HasColumnName("iIdReporte");
            entity.Property(e => e.DtFechaReporte)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("dtFechaReporte");
            entity.Property(e => e.NvchCategoria)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("nvchCategoria");
            entity.Property(e => e.NvchDescripcion)
                .IsRequired()
                .HasColumnName("nvchDescripcion");
            entity.Property(e => e.NvchEmail)
                .HasMaxLength(150)
                .HasColumnName("nvchEmail");
            entity.Property(e => e.NvchNombreCiudadano)
                .IsRequired()
                .HasMaxLength(150)
                .HasColumnName("nvchNombreCiudadano");
            entity.Property(e => e.NvchTelefono)
                .HasMaxLength(50)
                .HasColumnName("nvchTelefono");
            entity.Property(e => e.NvchThreadId)
                .HasMaxLength(100)
                .HasColumnName("nvchThreadId");
        });

        modelBuilder.Entity<Catalogo>(entity =>
        {
            entity.HasKey(e => e.IdCatalogo).HasName("PK_Catalogos_1");

            entity.Property(e => e.IdCatalogo).HasColumnName("Id_Catalogo");
            entity.Property(e => e.Descripcion)
                .IsRequired()
                .HasMaxLength(250)
                .UseCollation("Modern_Spanish_CI_AS");
            entity.Property(e => e.IdGrupo).HasColumnName("Id_Grupo");
            entity.Property(e => e.Valor)
                .HasMaxLength(50)
                .UseCollation("Modern_Spanish_CI_AS");

            entity.HasOne(d => d.IdGrupoNavigation).WithMany(p => p.Catalogos)
                .HasForeignKey(d => d.IdGrupo)
                .HasConstraintName("FK_Catalogos_Grupos");
        });

        modelBuilder.Entity<CategoriaNoticium>(entity =>
        {
            entity.HasKey(e => e.IIdCategoria);

            entity.Property(e => e.IIdCategoria).HasColumnName("iIdCategoria");
            entity.Property(e => e.BActivo)
                .HasDefaultValue(true)
                .HasColumnName("bActivo");
            entity.Property(e => e.VchColorHex)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("vchColorHex");
            entity.Property(e => e.VchNombre)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("vchNombre");
        });

        modelBuilder.Entity<Chat>(entity =>
        {
            entity.HasKey(e => e.IIdChat).HasName("PK__Chat__4ABD300836E888FA");

            entity.ToTable("Chat");

            entity.Property(e => e.IIdChat).HasColumnName("iIdChat");
            entity.Property(e => e.BActivo).HasColumnName("bActivo");
            entity.Property(e => e.DtFechaCreacion)
                .HasColumnType("datetime")
                .HasColumnName("dtFechaCreacion");
            entity.Property(e => e.IIdProyecto)
                .HasDefaultValue(12)
                .HasColumnName("iIdProyecto");
            entity.Property(e => e.NvchNombre)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("nvchNombre");
            entity.Property(e => e.NvchThreadId)
                .IsRequired()
                .HasMaxLength(100)
                .HasDefaultValue("")
                .HasColumnName("nvchThreadId");

            entity.HasOne(d => d.IIdProyectoNavigation).WithMany(p => p.Chats)
                .HasForeignKey(d => d.IIdProyecto)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Chat_Proyecto");
        });

        modelBuilder.Entity<Documento>(entity =>
        {
            entity.HasKey(e => e.IIdDocumento).HasName("PK__Document__8EDB9678F17966D9");

            entity.ToTable("Documento");

            entity.Property(e => e.IIdDocumento).HasColumnName("iIdDocumento");
            entity.Property(e => e.BActivo)
                .HasDefaultValue(true)
                .HasColumnName("bActivo");
            entity.Property(e => e.IIdTramite).HasColumnName("iIdTramite");
            entity.Property(e => e.VchNombre)
                .IsRequired()
                .HasMaxLength(250)
                .IsUnicode(false)
                .HasColumnName("vchNombre");
            entity.Property(e => e.VchUrl)
                .HasMaxLength(500)
                .IsUnicode(false)
                .HasColumnName("vchUrl");

            entity.HasOne(d => d.IIdTramiteNavigation).WithMany(p => p.Documentos)
                .HasForeignKey(d => d.IIdTramite)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Documento_Tramite");
        });

        modelBuilder.Entity<Fase>(entity =>
        {
            entity.HasKey(e => e.IIdFase).HasName("PK__Fase__C4448E757BA895AA");

            entity.ToTable("Fase");

            entity.Property(e => e.IIdFase).HasColumnName("iIdFase");
            entity.Property(e => e.DtActualizadoEn)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("dtActualizadoEn");
            entity.Property(e => e.DtCreadoEn)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("dtCreadoEn");
            entity.Property(e => e.IIdProyecto).HasColumnName("iIdProyecto");
            entity.Property(e => e.NvchDescripcion)
                .IsRequired()
                .HasColumnName("nvchDescripcion");
            entity.Property(e => e.NvchTitulo)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("nvchTitulo");
            entity.Property(e => e.SmNumeroSecuencia).HasColumnName("smNumeroSecuencia");

            entity.HasOne(d => d.IIdProyectoNavigation).WithMany(p => p.Fases)
                .HasForeignKey(d => d.IIdProyecto)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Fase_Proyecto");
        });

        modelBuilder.Entity<Funcionalidad>(entity =>
        {
            entity.HasKey(e => e.IIdFuncionalidad);

            entity.ToTable("Funcionalidad");

            entity.Property(e => e.IIdFuncionalidad).HasColumnName("iIdFuncionalidad");
            entity.Property(e => e.IIdModulo).HasColumnName("iIdModulo");
            entity.Property(e => e.NvchConsideraciones)
                .HasMaxLength(2000)
                .HasColumnName("nvchConsideraciones");
            entity.Property(e => e.NvchDescripcion)
                .IsRequired()
                .HasMaxLength(1000)
                .HasColumnName("nvchDescripcion");
            entity.Property(e => e.NvchEntidades)
                .HasMaxLength(400)
                .HasColumnName("nvchEntidades");
            entity.Property(e => e.NvchInteracciones)
                .HasMaxLength(1000)
                .HasColumnName("nvchInteracciones");
            entity.Property(e => e.NvchTecnico)
                .HasMaxLength(2000)
                .HasColumnName("nvchTecnico");

            entity.HasOne(d => d.IIdModuloNavigation).WithMany(p => p.Funcionalidads)
                .HasForeignKey(d => d.IIdModulo)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Funcionalidad_Modulo");
        });

        modelBuilder.Entity<Grupo>(entity =>
        {
            entity.HasKey(e => e.IdGrupo);

            entity.HasIndex(e => e.Alias, "UQ_Grupos_Alias").IsUnique();

            entity.Property(e => e.IdGrupo).HasColumnName("Id_Grupo");
            entity.Property(e => e.Alias)
                .IsRequired()
                .HasMaxLength(100)
                .UseCollation("Modern_Spanish_CI_AS");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(250)
                .UseCollation("Modern_Spanish_CI_AS");
        });

        modelBuilder.Entity<HistorialConsultum>(entity =>
        {
            entity.HasKey(e => e.IIdHistorial).HasName("PK__Historia__6D1A674ACCF20F68");

            entity.HasIndex(e => e.DtFecha, "IX_HistorialConsulta_dtFecha");

            entity.HasIndex(e => e.IIdUsuario, "IX_HistorialConsulta_iIdUsuario");

            entity.Property(e => e.IIdHistorial).HasColumnName("iIdHistorial");
            entity.Property(e => e.BAnonimizado).HasColumnName("bAnonimizado");
            entity.Property(e => e.DtFecha)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("dtFecha");
            entity.Property(e => e.IIdUsuario).HasColumnName("iIdUsuario");
            entity.Property(e => e.NvchPregunta)
                .IsRequired()
                .HasColumnName("nvchPregunta");
            entity.Property(e => e.NvchRespuesta)
                .IsRequired()
                .HasColumnName("nvchRespuesta");
            entity.Property(e => e.VchIntent)
                .HasMaxLength(150)
                .IsUnicode(false)
                .HasColumnName("vchIntent");
            entity.Property(e => e.VchOrigen)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("vchOrigen");
            entity.Property(e => e.VchSessionId)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("vchSessionId");
        });

        modelBuilder.Entity<Inventario>(entity =>
        {
            entity.HasKey(e => e.IIdInventario).HasName("PK__Inventar__7E4E1D6EE9EBECE6");

            entity.ToTable("Inventario");

            entity.Property(e => e.IIdInventario).HasColumnName("iIdInventario");
            entity.Property(e => e.IIdArticulo).HasColumnName("iIdArticulo");
            entity.Property(e => e.SmApartados).HasColumnName("smApartados");
            entity.Property(e => e.SmCantidad).HasColumnName("smCantidad");

            entity.HasOne(d => d.IIdArticuloNavigation).WithMany(p => p.Inventarios)
                .HasForeignKey(d => d.IIdArticulo)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Inventari__iIdAr__55209ACA");
        });

        modelBuilder.Entity<Mensaje>(entity =>
        {
            entity.HasKey(e => e.IIdMensaje).HasName("PK__Mensaje__DD49825384A32CA6");

            entity.ToTable("Mensaje");

            entity.Property(e => e.IIdMensaje).HasColumnName("iIdMensaje");
            entity.Property(e => e.DtFecha)
                .HasColumnType("datetime")
                .HasColumnName("dtFecha");
            entity.Property(e => e.IIdChat).HasColumnName("iIdChat");
            entity.Property(e => e.IIdFase).HasColumnName("iIdFase");
            entity.Property(e => e.IOrden).HasColumnName("iOrden");
            entity.Property(e => e.NvchContenido)
                .IsRequired()
                .HasColumnName("nvchContenido");
            entity.Property(e => e.NvchRol)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("nvchRol");

            entity.HasOne(d => d.IIdChatNavigation).WithMany(p => p.Mensajes)
                .HasForeignKey(d => d.IIdChat)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Mensaje_Chat");

            entity.HasOne(d => d.IIdFaseNavigation).WithMany(p => p.Mensajes)
                .HasForeignKey(d => d.IIdFase)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Mensaje_Fase");
        });

        modelBuilder.Entity<Modulo>(entity =>
        {
            entity.HasKey(e => e.IIdModulo);

            entity.ToTable("Modulo");

            entity.Property(e => e.IIdModulo).HasColumnName("iIdModulo");
            entity.Property(e => e.IIdPlanTrabajo).HasColumnName("iIdPlanTrabajo");
            entity.Property(e => e.NvchProposito)
                .HasMaxLength(4000)
                .HasColumnName("nvchProposito");
            entity.Property(e => e.VchTitulo)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("vchTitulo");

            entity.HasOne(d => d.IIdPlanTrabajoNavigation).WithMany(p => p.Modulos)
                .HasForeignKey(d => d.IIdPlanTrabajo)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Modulo_PlanTrabajo");
        });

        modelBuilder.Entity<Noticia>(entity =>
        {
            entity.HasKey(e => e.IIdNoticia).HasName("PK__Noticias__2CD882D9C915EF83");

            entity.Property(e => e.IIdNoticia).HasColumnName("iIdNoticia");
            entity.Property(e => e.BActivo)
                .HasDefaultValue(true)
                .HasColumnName("bActivo");
            entity.Property(e => e.DtFechaPublicacion)
                .HasColumnType("datetime")
                .HasColumnName("dtFechaPublicacion");
            entity.Property(e => e.IIdCategoria).HasColumnName("iIdCategoria");
            entity.Property(e => e.NvchContenido)
                .IsRequired()
                .HasColumnName("nvchContenido");
            entity.Property(e => e.NvchContenidoEn).HasColumnName("nvchContenidoEn");
            entity.Property(e => e.VchImagenPortada)
                .HasMaxLength(500)
                .IsUnicode(false)
                .HasColumnName("vchImagenPortada");
            entity.Property(e => e.VchTitulo)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("vchTitulo");
            entity.Property(e => e.VchTituloEn)
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("vchTituloEn");

            entity.HasOne(d => d.IIdCategoriaNavigation).WithMany(p => p.Noticia)
                .HasForeignKey(d => d.IIdCategoria)
                .HasConstraintName("FK_Noticias_CategoriaNoticia");
        });

        modelBuilder.Entity<NoticiaFila>(entity =>
        {
            entity.HasKey(e => e.IIdFila);

            entity.ToTable("NoticiaFila");

            entity.Property(e => e.IIdFila).HasColumnName("iIdFila");
            entity.Property(e => e.IIdNoticia).HasColumnName("iIdNoticia");
            entity.Property(e => e.IOrden).HasColumnName("iOrden");

            entity.HasOne(d => d.IIdNoticiaNavigation).WithMany(p => p.NoticiaFilas)
                .HasForeignKey(d => d.IIdNoticia)
                .HasConstraintName("FK_NoticiaFila_Noticia");
        });

        modelBuilder.Entity<NoticiaMetadato>(entity =>
        {
            entity.HasKey(e => e.IIdMetadato);

            entity.ToTable("NoticiaMetadato");

            entity.Property(e => e.IIdMetadato).HasColumnName("iIdMetadato");
            entity.Property(e => e.IAncho).HasColumnName("iAncho");
            entity.Property(e => e.IIdFila).HasColumnName("iIdFila");
            entity.Property(e => e.IIdNoticia).HasColumnName("iIdNoticia");
            entity.Property(e => e.IIdTipoDato).HasColumnName("iIdTipoDato");
            entity.Property(e => e.IOrden).HasColumnName("iOrden");
            entity.Property(e => e.NvchConfiguracion).HasColumnName("nvchConfiguracion");
            entity.Property(e => e.NvchValor)
                .IsRequired()
                .HasColumnName("nvchValor");
            entity.Property(e => e.VchAlineacion)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("vchAlineacion");
            entity.Property(e => e.VchAlto)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("vchAlto");
            entity.Property(e => e.VchTitulo)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("vchTitulo");

            entity.HasOne(d => d.IIdFilaNavigation).WithMany(p => p.NoticiaMetadatos)
                .HasForeignKey(d => d.IIdFila)
                .HasConstraintName("FK_NoticiaMetadato_NoticiaFila");

            entity.HasOne(d => d.IIdNoticiaNavigation).WithMany(p => p.NoticiaMetadatos)
                .HasForeignKey(d => d.IIdNoticia)
                .HasConstraintName("FK_NoticiaMetadato_Noticias");

            entity.HasOne(d => d.IIdTipoDatoNavigation).WithMany(p => p.NoticiaMetadatos)
                .HasForeignKey(d => d.IIdTipoDato)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_NoticiaMetadato_Catalogos");
        });

        modelBuilder.Entity<NoticiasImagene>(entity =>
        {
            entity.HasKey(e => e.IIdNoticiaImagen).HasName("PK__Noticias__6EE3866A8A7D4DDA");

            entity.ToTable("Noticias_Imagenes");

            entity.Property(e => e.IIdNoticiaImagen).HasColumnName("iIdNoticiaImagen");
            entity.Property(e => e.IIdNoticia).HasColumnName("iIdNoticia");
            entity.Property(e => e.VchUrlImagen)
                .IsRequired()
                .HasMaxLength(500)
                .IsUnicode(false)
                .HasColumnName("vchUrlImagen");

            entity.HasOne(d => d.IIdNoticiaNavigation).WithMany(p => p.NoticiasImagenes)
                .HasForeignKey(d => d.IIdNoticia)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Noticias___iIdNo__679450C0");
        });

        modelBuilder.Entity<Oficina>(entity =>
        {
            entity.HasKey(e => e.IIdOficina).HasName("PK__Oficina__B124A2030D3916D5");

            entity.ToTable("Oficina");

            entity.HasIndex(e => new { e.FlLatitud, e.FlLongitud }, "IX_Oficina_LatLong");

            entity.HasIndex(e => e.VchDireccion, "IX_Oficina_vchDireccion");

            entity.HasIndex(e => e.VchNombre, "IX_Oficina_vchNombre");

            entity.Property(e => e.IIdOficina).HasColumnName("iIdOficina");
            entity.Property(e => e.BActivo)
                .HasDefaultValue(true)
                .HasColumnName("bActivo");
            entity.Property(e => e.DtFechaCreacion)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("dtFechaCreacion");
            entity.Property(e => e.FlLatitud).HasColumnName("flLatitud");
            entity.Property(e => e.FlLongitud).HasColumnName("flLongitud");
            entity.Property(e => e.VchDireccion)
                .HasMaxLength(500)
                .IsUnicode(false)
                .HasColumnName("vchDireccion");
            entity.Property(e => e.VchEmail)
                .HasMaxLength(150)
                .IsUnicode(false)
                .HasColumnName("vchEmail");
            entity.Property(e => e.VchHorario)
                .HasMaxLength(250)
                .HasColumnName("vchHorario");
            entity.Property(e => e.VchNombre)
                .IsRequired()
                .HasMaxLength(250)
                .IsUnicode(false)
                .HasColumnName("vchNombre");
            entity.Property(e => e.VchNotas).HasColumnName("vchNotas");
            entity.Property(e => e.VchTelefono)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("vchTelefono");
            entity.Property(e => e.VchUrlDireccion)
                .HasMaxLength(255)
                .HasColumnName("vchUrlDireccion");
        });

        modelBuilder.Entity<OficinaTramite>(entity =>
        {
            entity.HasKey(e => e.IIdOficinaTramite).HasName("PK__OficinaT__E17177D125D89207");

            entity.ToTable("OficinaTramite");

            entity.Property(e => e.IIdOficinaTramite).HasColumnName("iIdOficinaTramite");
            entity.Property(e => e.BActivo)
                .HasDefaultValue(true)
                .HasColumnName("bActivo");
            entity.Property(e => e.DtFechaCreacion)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("dtFechaCreacion");
            entity.Property(e => e.IIdOficina).HasColumnName("iIdOficina");
            entity.Property(e => e.IIdTramite).HasColumnName("iIdTramite");
            entity.Property(e => e.VchObservacion)
                .HasMaxLength(500)
                .HasColumnName("vchObservacion");

            entity.HasOne(d => d.IIdOficinaNavigation).WithMany(p => p.OficinaTramites)
                .HasForeignKey(d => d.IIdOficina)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OficinaTramite_Oficina");

            entity.HasOne(d => d.IIdTramiteNavigation).WithMany(p => p.OficinaTramites)
                .HasForeignKey(d => d.IIdTramite)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OficinaTramite_Tramite");
        });

        modelBuilder.Entity<Paso>(entity =>
        {
            entity.HasKey(e => e.IIdPaso).HasName("PK__Paso__5BE7D37DD6137ED0");

            entity.ToTable("Paso");

            entity.Property(e => e.IIdPaso).HasColumnName("iIdPaso");
            entity.Property(e => e.DtActualizadoEn)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("dtActualizadoEn");
            entity.Property(e => e.DtCreadoEn)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("dtCreadoEn");
            entity.Property(e => e.IIdFase).HasColumnName("iIdFase");
            entity.Property(e => e.NvchCaracteristicas)
                .IsRequired()
                .HasColumnName("nvchCaracteristicas");
            entity.Property(e => e.NvchDescripcion)
                .IsRequired()
                .HasColumnName("nvchDescripcion");
            entity.Property(e => e.NvchEnfoque)
                .IsRequired()
                .HasColumnName("nvchEnfoque");
            entity.Property(e => e.NvchProposito)
                .IsRequired()
                .HasColumnName("nvchProposito");
            entity.Property(e => e.SmNumeroSecuencia).HasColumnName("smNumeroSecuencia");

            entity.HasOne(d => d.IIdFaseNavigation).WithMany(p => p.Pasos)
                .HasForeignKey(d => d.IIdFase)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Paso_Fase");
        });

        modelBuilder.Entity<Pedido>(entity =>
        {
            entity.HasKey(e => e.IIdPedido).HasName("PK__Pedido__F86531235CD94589");

            entity.ToTable("Pedido");

            entity.Property(e => e.IIdPedido).HasColumnName("iIdPedido");
            entity.Property(e => e.DtFecha)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("dtFecha");
            entity.Property(e => e.IIdProveedor).HasColumnName("iIdProveedor");
            entity.Property(e => e.MEnvio)
                .HasColumnType("money")
                .HasColumnName("mEnvio");
            entity.Property(e => e.NvchDescripcion)
                .HasMaxLength(3000)
                .HasColumnName("nvchDescripcion");

            entity.HasOne(d => d.IIdProveedorNavigation).WithMany(p => p.Pedidos)
                .HasForeignKey(d => d.IIdProveedor)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Pedido__iIdProve__4C8B54C9");
        });

        modelBuilder.Entity<PedidoDetalle>(entity =>
        {
            entity.HasKey(e => e.IIdPedidoDetalle).HasName("PK__PedidoDe__CFA44428A99366F0");

            entity.ToTable("PedidoDetalle");

            entity.Property(e => e.IIdPedidoDetalle).HasColumnName("iIdPedidoDetalle");
            entity.Property(e => e.IIdArticulo).HasColumnName("iIdArticulo");
            entity.Property(e => e.IIdPedido).HasColumnName("iIdPedido");
            entity.Property(e => e.MPrecioUnitario)
                .HasColumnType("money")
                .HasColumnName("mPrecioUnitario");
            entity.Property(e => e.SmCantidad).HasColumnName("smCantidad");

            entity.HasOne(d => d.IIdArticuloNavigation).WithMany(p => p.PedidoDetalles)
                .HasForeignKey(d => d.IIdArticulo)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__PedidoDet__iIdAr__515009E6");

            entity.HasOne(d => d.IIdPedidoNavigation).WithMany(p => p.PedidoDetalles)
                .HasForeignKey(d => d.IIdPedido)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__PedidoDet__iIdPe__505BE5AD");
        });

        modelBuilder.Entity<PlanTrabajo>(entity =>
        {
            entity.HasKey(e => e.IIdPlanTrabajo);

            entity.ToTable("PlanTrabajo");

            entity.Property(e => e.IIdPlanTrabajo).HasColumnName("iIdPlanTrabajo");
            entity.Property(e => e.NvchDescripcion)
                .IsRequired()
                .HasMaxLength(4000)
                .HasColumnName("nvchDescripcion");
            entity.Property(e => e.VchEstatus)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("vchEstatus");
            entity.Property(e => e.VchNombre)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("vchNombre");
        });

        modelBuilder.Entity<Proveedor>(entity =>
        {
            entity.HasKey(e => e.IIdProveedor).HasName("PK__Proveedo__DA7D8647F241EB3A");

            entity.ToTable("Proveedor");

            entity.Property(e => e.IIdProveedor).HasColumnName("iIdProveedor");
            entity.Property(e => e.NvchDireccion)
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnName("nvchDireccion");
            entity.Property(e => e.NvchNombre)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("nvchNombre");
            entity.Property(e => e.VchTelefono)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("vchTelefono");
        });

        modelBuilder.Entity<Proyecto>(entity =>
        {
            entity.HasKey(e => e.IIdProyecto).HasName("PK__Proyecto__11700809B17F6124");

            entity.ToTable("Proyecto");

            entity.Property(e => e.IIdProyecto).HasColumnName("iIdProyecto");
            entity.Property(e => e.DtActualizadoEn)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("dtActualizadoEn");
            entity.Property(e => e.DtCreadoEn)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("dtCreadoEn");
            entity.Property(e => e.IIdPlanTrabajo).HasColumnName("iIdPlanTrabajo");
            entity.Property(e => e.NvchDescripcion)
                .IsRequired()
                .HasColumnName("nvchDescripcion");
            entity.Property(e => e.NvchNombre)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("nvchNombre");

            entity.HasOne(d => d.IIdPlanTrabajoNavigation).WithMany(p => p.Proyectos)
                .HasForeignKey(d => d.IIdPlanTrabajo)
                .HasConstraintName("FK_Proyecto_PlanTrabajo");
        });

        modelBuilder.Entity<Requisito>(entity =>
        {
            entity.HasKey(e => e.IIdRequisito).HasName("PK__Requisit__2DAC3027B0699F39");

            entity.ToTable("Requisito");

            entity.Property(e => e.IIdRequisito).HasColumnName("iIdRequisito");
            entity.Property(e => e.BActivo)
                .HasDefaultValue(true)
                .HasColumnName("bActivo");
            entity.Property(e => e.BObligatorio)
                .HasDefaultValue(true)
                .HasColumnName("bObligatorio");
            entity.Property(e => e.IIdTramite).HasColumnName("iIdTramite");
            entity.Property(e => e.NvchDetalle)
                .HasMaxLength(1000)
                .HasColumnName("nvchDetalle");
            entity.Property(e => e.VchNombre)
                .IsRequired()
                .HasMaxLength(250)
                .IsUnicode(false)
                .HasColumnName("vchNombre");

            entity.HasOne(d => d.IIdTramiteNavigation).WithMany(p => p.Requisitos)
                .HasForeignKey(d => d.IIdTramite)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Requisito_Tramite");
        });

        modelBuilder.Entity<TestTable>(entity =>
        {
            entity.HasKey(e => e.IIdTestTable);

            entity.ToTable("Test_Table");

            entity.Property(e => e.IIdTestTable).HasColumnName("iIdTest_Table");
            entity.Property(e => e.DtRegistered)
                .HasColumnType("datetime")
                .HasColumnName("dtRegistered");
            entity.Property(e => e.VchEmail)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("vchEmail");
            entity.Property(e => e.VchName)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("vchName");
        });

        modelBuilder.Entity<TipoDato>(entity =>
        {
            entity.HasKey(e => e.IIdTipoDato).HasName("PK_Tipo_Datos");

            entity.Property(e => e.IIdTipoDato).HasColumnName("iIdTipoDato");
            entity.Property(e => e.NcvhDescripcion)
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("ncvhDescripcion");
            entity.Property(e => e.NvchTipo)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("nvchTipo");
        });

        modelBuilder.Entity<Tramite>(entity =>
        {
            entity.HasKey(e => e.IIdTramite).HasName("PK__Tramite__5EB01175642DB1DB");

            entity.ToTable("Tramite");

            entity.HasIndex(e => e.DtFechaCreacion, "IX_Tramite_dtFechaCreacion").IsDescending();

            entity.HasIndex(e => e.VchNombre, "IX_Tramite_vchNombre");

            entity.Property(e => e.IIdTramite).HasColumnName("iIdTramite");
            entity.Property(e => e.BActivo)
                .HasDefaultValue(true)
                .HasColumnName("bActivo");
            entity.Property(e => e.BModalidadEnLinea).HasColumnName("bModalidadEnLinea");
            entity.Property(e => e.DtFechaActualizacion)
                .HasColumnType("datetime")
                .HasColumnName("dtFechaActualizacion");
            entity.Property(e => e.DtFechaCreacion)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("dtFechaCreacion");
            entity.Property(e => e.IIdCategoria).HasColumnName("iIdCategoria");
            entity.Property(e => e.IIdOficina).HasColumnName("iIdOficina");
            entity.Property(e => e.MCosto)
                .HasColumnType("money")
                .HasColumnName("mCosto");
            entity.Property(e => e.NvchDescripcion)
                .IsRequired()
                .HasColumnName("nvchDescripcion");
            entity.Property(e => e.NvchDescripcionEn).HasColumnName("nvchDescripcionEn");
            entity.Property(e => e.VchNombre)
                .IsRequired()
                .HasMaxLength(250)
                .IsUnicode(false)
                .HasColumnName("vchNombre");
            entity.Property(e => e.VchNombreEn)
                .HasMaxLength(250)
                .IsUnicode(false)
                .HasColumnName("vchNombreEn");
        });

        modelBuilder.Entity<TramitePaso>(entity =>
        {
            entity.HasKey(e => e.IIdTramitePaso).HasName("PK__TramiteP__6851F9586D3C524A");

            entity.ToTable("TramitePaso");

            entity.Property(e => e.IIdTramitePaso).HasColumnName("iIdTramitePaso");
            entity.Property(e => e.BActivo)
                .HasDefaultValue(true)
                .HasColumnName("bActivo");
            entity.Property(e => e.IIdTramite).HasColumnName("iIdTramite");
            entity.Property(e => e.IOrden).HasColumnName("iOrden");
            entity.Property(e => e.NvchDescripcion)
                .IsRequired()
                .HasMaxLength(1000)
                .HasColumnName("nvchDescripcion");

            entity.HasOne(d => d.IIdTramiteNavigation).WithMany(p => p.TramitePasos)
                .HasForeignKey(d => d.IIdTramite)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TramitePaso_Tramite");
        });

        modelBuilder.Entity<Usuario>(entity =>
        {
            entity.HasKey(e => e.IIdUsuario).HasName("PK__Usuario__A271047FABB33DCE");

            entity.ToTable("Usuario");

            entity.Property(e => e.IIdUsuario).HasColumnName("iIdUsuario");
            entity.Property(e => e.BActivo)
                .HasDefaultValue(true)
                .HasColumnName("bActivo");
            entity.Property(e => e.DtFechaRegistro)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("dtFechaRegistro");
            entity.Property(e => e.NvchCorreo)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("nvchCorreo");
            entity.Property(e => e.NvchNombre)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("nvchNombre");
            entity.Property(e => e.NvchPassword)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("nvchPassword");
            entity.Property(e => e.VchTelefono)
                .IsRequired()
                .HasMaxLength(15)
                .IsUnicode(false)
                .HasColumnName("vchTelefono");
        });

        modelBuilder.Entity<Ventum>(entity =>
        {
            entity.HasKey(e => e.IIdVenta).HasName("PK__Venta__5648A3B22089A929");

            entity.Property(e => e.IIdVenta).HasColumnName("iIdVenta");
            entity.Property(e => e.DtFechaVenta)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Venta_Fecha")
                .HasColumnType("datetime")
                .HasColumnName("dtFechaVenta");
            entity.Property(e => e.ICantidad).HasColumnName("iCantidad");
            entity.Property(e => e.IIdArticulo).HasColumnName("iIdArticulo");
            entity.Property(e => e.MPrecioFinal)
                .HasColumnType("money")
                .HasColumnName("mPrecioFinal");
            entity.Property(e => e.VchReferenciaVenta)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("vchReferenciaVenta");

            entity.HasOne(d => d.IIdArticuloNavigation).WithMany(p => p.Venta)
                .HasForeignKey(d => d.IIdArticulo)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Venta_Articulo");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}