// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SantiagoConectaIA.DAL.Models;

public partial class Fase
{
    public int IIdFase { get; set; }

    public int IIdProyecto { get; set; }

    public short SmNumeroSecuencia { get; set; }

    public string NvchTitulo { get; set; }

    public string NvchDescripcion { get; set; }

    public DateTime DtCreadoEn { get; set; }

    public DateTime DtActualizadoEn { get; set; }

    public virtual Proyecto IIdProyectoNavigation { get; set; }

    public virtual ICollection<Mensaje> Mensajes { get; set; } = new List<Mensaje>();

    public virtual ICollection<Paso> Pasos { get; set; } = new List<Paso>();
}