// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SantiagoConectaIA.DAL.Models;

public partial class Funcionalidad
{
    public int IIdFuncionalidad { get; set; }

    public int IIdModulo { get; set; }

    public string NvchDescripcion { get; set; }

    public string NvchEntidades { get; set; }

    public string NvchInteracciones { get; set; }

    public string NvchTecnico { get; set; }

    public string NvchConsideraciones { get; set; }

    public virtual Modulo IIdModuloNavigation { get; set; }
}