// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SantiagoConectaIA.DAL.Models;

public partial class HistorialConsultum
{
    public int IIdHistorial { get; set; }

    public int? IIdUsuario { get; set; }

    public string NvchPregunta { get; set; }

    public string NvchRespuesta { get; set; }

    public string VchOrigen { get; set; }

    public string VchSessionId { get; set; }

    public string VchIntent { get; set; }

    public bool BAnonimizado { get; set; }

    public DateTime DtFecha { get; set; }
}