// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using SantiagoConectaIA.DAL.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Reflection;
using System.Threading;
using System.Threading.Tasks;

namespace SantiagoConectaIA.DAL.Models
{
    public partial interface IEngramaContextProcedures
    {
        Task<List<spDeletePedidoDetalleResult>> spDeletePedidoDetalleAsync(int? iIdPedidoDetalle, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetAbonoApartadoResult>> spGetAbonoApartadoAsync(int? iIdApartado, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetApartadoResult>> spGetApartadoAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetApartadoDetalleResult>> spGetApartadoDetalleAsync(int? iIdApartado, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetArticuloResult>> spGetArticuloAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetChatResult>> spGetChatAsync(int? iIdProyecto, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetDependenciasResult>> spGetDependenciasAsync(int? iIdDependencia, bool? bActivo, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetDocumentosPorTramiteResult>> spGetDocumentosPorTramiteAsync(int? iIdTramite, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetED_DescripcionResult>> spGetED_DescripcionAsync(int? iIdED_Proceso, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetED_ProcesoResult>> spGetED_ProcesoAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetFaseResult>> spGetFaseAsync(int? iIdProyecto, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetFuncionalidadResult>> spGetFuncionalidadAsync(int? iIdModulo, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetInventarioResult>> spGetInventarioAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetMensajeResult>> spGetMensajeAsync(int? iIdChat, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetModuloResult>> spGetModuloAsync(int? iIdPlanTrabajo, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetNoticiasResult>> spGetNoticiasAsync(bool? bActivo, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetOficinasResult>> spGetOficinasAsync(int? iIdOficina, bool? bActivo, bool? bIncluirContacto, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetOficinasPorTramiteResult>> spGetOficinasPorTramiteAsync(int? iIdTramite, string vchTexto, bool? bIncluirContacto, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetPasoResult>> spGetPasoAsync(int? iIdFase, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetPasosPorTramiteResult>> spGetPasosPorTramiteAsync(int? iIdTramite, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetPedidoResult>> spGetPedidoAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetPedidoDetalleResult>> spGetPedidoDetalleAsync(int? iIdPedido, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetPlanTrabajoResult>> spGetPlanTrabajoAsync(int? iIdPlanTrabajo, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetProveedorResult>> spGetProveedorAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetProyectoResult>> spGetProyectoAsync(int? iIdProyecto, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetRequisitosPorTramiteResult>> spGetRequisitosPorTramiteAsync(int? iIdTramite, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetTestTableResult>> spGetTestTableAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetTestTableDataTypeResult>> spGetTestTableDataTypeAsync(int? iIdTest_Table, string vchName, string vchEmail, DateTime? dtRegistered, IEnumerable<DTParameterType> parameters, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetTestTableOneResultResult>> spGetTestTableOneResultAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetTestTableParametersResult>> spGetTestTableParametersAsync(int? iParameter, string vchParameter, DateTime? dtParameter, decimal? mParametr, short? smParameter, bool? bParameter, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetTramiteDetalleResult>> spGetTramiteDetalleAsync(int? iIdTramite, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetTramitesResult>> spGetTramitesAsync(int? iIdTramite, bool? bActivo, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetTramitesCardResult>> spGetTramitesCardAsync(int? iIdTramite, bool? bActivo, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetUsuarioResult>> spGetUsuarioAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetVentaResult>> spGetVentaAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spLinkOficinaTramiteResult>> spLinkOficinaTramiteAsync(int? iIdOficina, int? iIdTramite, string vchObservacion, bool? bActivo, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spSaveAbonoApartadoResult>> spSaveAbonoApartadoAsync(int? iIdApartado, decimal? mAbono, OutputParameter<int?> iIdAbonoApartado, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spSaveApartadoResult>> spSaveApartadoAsync(int? iIdApartado, string nvchNombreCliente, decimal? mTotal, bool? bPagado, string nvchComentario, IEnumerable<DTApartadoDetalle> detalles, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spSaveArticuloResult>> spSaveArticuloAsync(int? iIdArticulo, int? iIdProveedor, string nvchNombre, string vchCodigo, string nvchDescripcion, decimal? mPrecioCompra, decimal? mPrecioVenta, short? smCantidad, bool? bActivo, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spSaveChatResult>> spSaveChatAsync(int? iIdChat, int? iIdProyecto, DateTime? dtFechaCreacion, string nvchNombre, bool? bActivo, string nvchThreadId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spSaveDocumentoResult>> spSaveDocumentoAsync(int? iIdDocumento, int? iIdTramite, string vchNombre, string vchUrlDocumento, bool? bActivo, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spSaveED_DescripcionResult>> spSaveED_DescripcionAsync(int? iIdED_Descripcion, int? iIdED_Proceso, string vchTitulo, string vchDescripcion, string vchDescripcionIngles, int? iIdED_Imagenes, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spSaveED_ImagenesResult>> spSaveED_ImagenesAsync(int? iIdED_Imagenes, string vchImagen, string vchDescripcion, string vchDescripcionIngles, string vchAlt, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spSaveED_ProcesoResult>> spSaveED_ProcesoAsync(int? iIdED_Proceso, string vchTitle, string vchDescripcion, string vchDescripcionIngles, string vchImage, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spSaveFaseResult>> spSaveFaseAsync(int? iIdFase, int? iIdProyecto, short? smNumeroSecuencia, string nvchTitulo, string nvchDescripcion, DateTime? dtCreadoEn, DateTime? dtActualizadoEn, IEnumerable<DTPaso> lstPasos, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spSaveHistorialConsultaSimpleResult>> spSaveHistorialConsultaSimpleAsync(int? iIdUsuario, string nvchPregunta, string nvchRespuesta, string vchOrigen, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spSaveMensajeResult>> spSaveMensajeAsync(int? iIdMensaje, int? iIdChat, int? iOrden, int? iIdFase, string nvchRol, string nvchContenido, DateTime? dtFecha, string nvchThreadId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spSaveModuloResult>> spSaveModuloAsync(int? iIdModulo, int? iIdPlanTrabajo, string vchTitulo, string nvchProposito, IEnumerable<DTFuncionalidad> lstFuncionalidades, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spSaveNoticiaResult>> spSaveNoticiaAsync(int? iIdNoticia, string vchTitulo, string vchTituloEn, string nvchContenido, string nvchContenidoEn, string vchImagenPortada, DateTime? dtFechaPublicacion, bool? bActivo, int? iIdCategoria, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spSaveNoticiaImagenResult>> spSaveNoticiaImagenAsync(int? iIdNoticia, string vchUrlImagen, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spSaveOficinaResult>> spSaveOficinaAsync(int? iIdOficina, string vchNombre, string vchDireccion, string vchTelefono, string vchEmail, string vchHorario, double? flLatitud, double? flLongitud, string vchNotas, string vchUrlDireccion, bool? bActivo, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spSavePedidoResult>> spSavePedidoAsync(int? iIdPedido, int? iIdProveedor, string nvchDescripcion, decimal? mEnvio, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spSavePedidoDetalleResult>> spSavePedidoDetalleAsync(int? iIdPedido, int? iIdProveedor, int? iIdArticulo, short? smCantidad, decimal? mPrecioUnitario, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spSavePlanTrabajoResult>> spSavePlanTrabajoAsync(int? iIdPlanTrabajo, string vchNombre, string nvchDescripcion, string vchEstatus, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spSaveProveedorResult>> spSaveProveedorAsync(int? iIdProveedor, string nvchNombre, string vchTelefono, string nvchDireccion, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spSaveProyectoResult>> spSaveProyectoAsync(int? iIdProyecto, int? iIdPlanTrabajo, string nvchNombre, string nvchDescripcion, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spSaveRequisitoResult>> spSaveRequisitoAsync(int? iIdRequisito, int? iIdTramite, string vchNombre, string nvchDetalle, bool? bObligatorio, bool? bActivo, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spSaveTest_TableResult>> spSaveTest_TableAsync(int? iIdTest_Table, string vchName, string vchEmail, DateTime? dtRegistered, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spSaveTramiteResult>> spSaveTramiteAsync(int? iIdTramite, string vchNombre, string nvchDescripcion, string vchNombreEn, string nvchDescripcionEn, int? iIdCategoria, bool? bModalidadEnLinea, decimal? mCosto, int? iIdOficina, bool? bActivo, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spSaveVentaResult>> spSaveVentaAsync(int? iIdArticulo, int? iCantidad, decimal? mPrecioFinal, DateTime? dtFechaVenta, string vchReferenciaVenta, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spSearchCostoForChatResult>> spSearchCostoForChatAsync(int? iIdTramite, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spSearchOficinasResult>> spSearchOficinasAsync(string vchTexto, int? iPage, int? iPageSize, bool? bIncluirContacto, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spSearchOficinasByTramiteResult>> spSearchOficinasByTramiteAsync(int? iIdTramite, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spSearchOficinasForChatResult>> spSearchOficinasForChatAsync(string vchTexto, int? iLimit, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spSearchRequisitosForChatResult>> spSearchRequisitosForChatAsync(int? iIdTramite, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spSearchTramitesResult>> spSearchTramitesAsync(string vchTexto, int? iIdCategoria, int? iPage, int? iPageSize, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spSearchTramitesForChatResult>> spSearchTramitesForChatAsync(string vchTexto, int? iLimit, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
