// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SantiagoConectaIA.DAL.Models;

public partial class Mensaje
{
    public int IIdMensaje { get; set; }

    public int IIdChat { get; set; }

    public int IIdFase { get; set; }

    public int IOrden { get; set; }

    public string NvchRol { get; set; }

    public string NvchContenido { get; set; }

    public DateTime DtFecha { get; set; }

    public virtual Chat IIdChatNavigation { get; set; }

    public virtual Fase IIdFaseNavigation { get; set; }
}