// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SantiagoConectaIA.DAL.Models;

public partial class Modulo
{
    public int IIdModulo { get; set; }

    public int IIdPlanTrabajo { get; set; }

    public string VchTitulo { get; set; }

    public string NvchProposito { get; set; }

    public virtual ICollection<Funcionalidad> Funcionalidads { get; set; } = new List<Funcionalidad>();

    public virtual PlanTrabajo IIdPlanTrabajoNavigation { get; set; }
}