// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SantiagoConectaIA.DAL.Models;

public partial class NoticiasImagene
{
    public int IIdNoticiaImagen { get; set; }

    public int IIdNoticia { get; set; }

    public string VchUrlImagen { get; set; }

    public virtual Noticia IIdNoticiaNavigation { get; set; }
}