// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SantiagoConectaIA.DAL.Models;

public partial class NoticiaFila
{
    public int IIdFila { get; set; }

    public int IIdNoticia { get; set; }

    public int IOrden { get; set; }

    public virtual Noticia IIdNoticiaNavigation { get; set; }

    public virtual ICollection<NoticiaMetadato> NoticiaMetadatos { get; set; } = new List<NoticiaMetadato>();
}