// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SantiagoConectaIA.DAL.Models;

public partial class Noticia
{
    public int IIdNoticia { get; set; }

    public string VchTitulo { get; set; }

    public string VchTituloEn { get; set; }

    public string NvchContenido { get; set; }

    public string NvchContenidoEn { get; set; }

    public string VchImagenPortada { get; set; }

    public DateTime DtFechaPublicacion { get; set; }

    public bool BActivo { get; set; }

    public int? IIdCategoria { get; set; }

    public virtual CategoriaNoticium IIdCategoriaNavigation { get; set; }

    public virtual ICollection<NoticiaMetadato> NoticiaMetadatos { get; set; } = new List<NoticiaMetadato>();

    public virtual ICollection<NoticiasImagene> NoticiasImagenes { get; set; } = new List<NoticiasImagene>();
}