// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SantiagoConectaIA.DAL.Models;

public partial class NoticiaMetadato
{
    public int IIdMetadato { get; set; }

    public int IIdNoticia { get; set; }

    public int IIdTipoDato { get; set; }

    public string vchAlias { get; set; }

    public string NvchValor { get; set; }

    public int IOrden { get; set; }

    public virtual Noticia IIdNoticiaNavigation { get; set; }

    public virtual TipoDato IIdTipoDatoNavigation { get; set; }
}