// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SantiagoConectaIA.DAL.Models;

public partial class OficinaTramite
{
    public int IIdOficinaTramite { get; set; }

    public int IIdOficina { get; set; }

    public int IIdTramite { get; set; }

    public string VchObservacion { get; set; }

    public bool BActivo { get; set; }

    public DateTime DtFechaCreacion { get; set; }

    public virtual Oficina IIdOficinaNavigation { get; set; }

    public virtual Tramite IIdTramiteNavigation { get; set; }
}