// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SantiagoConectaIA.DAL.Models;

public partial class Parametro
{
    public int IIdParametro { get; set; }

    public int? IIdParametroPadre { get; set; }

    public string NvchAlias { get; set; }

    public string NvchNombre { get; set; }

    public string NvchNombreEn { get; set; }

    public string NvchDescripcion { get; set; }

    public string NvchDescripcionEn { get; set; }

    public int ISecuencia { get; set; }

    public bool BTieneValores { get; set; }

    public string NvchValor1 { get; set; }

    public string NvchValor2 { get; set; }

    public bool BHabilitado { get; set; }
}