// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SantiagoConectaIA.DAL.Models;

public partial class Paso
{
    public int IIdPaso { get; set; }

    public short SmNumeroSecuencia { get; set; }

    public string NvchDescripcion { get; set; }

    public string NvchProposito { get; set; }

    public string NvchCaracteristicas { get; set; }

    public string NvchEnfoque { get; set; }

    public DateTime DtCreadoEn { get; set; }

    public DateTime DtActualizadoEn { get; set; }
}