// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SantiagoConectaIA.DAL.Models;

public partial class Pedido
{
    public int IIdPedido { get; set; }

    public int IIdProveedor { get; set; }

    public DateTime DtFecha { get; set; }

    public string NvchDescripcion { get; set; }

    public decimal? MEnvio { get; set; }

    public virtual Proveedor IIdProveedorNavigation { get; set; }

    public virtual ICollection<PedidoDetalle> PedidoDetalles { get; set; } = new List<PedidoDetalle>();
}