// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SantiagoConectaIA.DAL.Models;

public partial class PedidoDetalle
{
    public int IIdPedidoDetalle { get; set; }

    public int IIdPedido { get; set; }

    public int IIdArticulo { get; set; }

    public short SmCantidad { get; set; }

    public decimal MPrecioUnitario { get; set; }

    public virtual Articulo IIdArticuloNavigation { get; set; }

    public virtual Pedido IIdPedidoNavigation { get; set; }
}