// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SantiagoConectaIA.DAL.Models;

public partial class PlanTrabajo
{
    public int IIdPlanTrabajo { get; set; }

    public string VchNombre { get; set; }

    public string NvchDescripcion { get; set; }

    public string VchEstatus { get; set; }

    public virtual ICollection<Modulo> Modulos { get; set; } = new List<Modulo>();

    public virtual ICollection<Proyecto> Proyectos { get; set; } = new List<Proyecto>();
}