// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SantiagoConectaIA.DAL.Models;

public partial class Proveedor
{
    public int IIdProveedor { get; set; }

    public string NvchNombre { get; set; }

    public string VchTelefono { get; set; }

    public string NvchDireccion { get; set; }

    public virtual ICollection<Articulo> Articulos { get; set; } = new List<Articulo>();

    public virtual ICollection<Pedido> Pedidos { get; set; } = new List<Pedido>();
}