// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SantiagoConectaIA.DAL.Models;

public partial class Proyecto
{
    public int IIdProyecto { get; set; }

    public string NvchNombre { get; set; }

    public string NvchDescripcion { get; set; }

    public DateTime DtCreadoEn { get; set; }

    public DateTime DtActualizadoEn { get; set; }

    public int? IIdPlanTrabajo { get; set; }

    public virtual ICollection<Chat> Chats { get; set; } = new List<Chat>();

    public virtual PlanTrabajo IIdPlanTrabajoNavigation { get; set; }
}