// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SantiagoConectaIA.DAL.Models
{
    public partial class spGetProyectoResult
    {
        public bool? bResult { get; set; }
        [StringLength(500)]
        public string vchMessage { get; set; }
        public int? iIdProyecto { get; set; }
        [StringLength(510)]
        public string nvchNombre { get; set; }
        [StringLength(2147483647)]
        public string nvchDescripcion { get; set; }
        public DateTime? dtCreadoEn { get; set; }
        public DateTime? dtActualizadoEn { get; set; }
        public int? iIdPlanTrabajo { get; set; }
    }
}
