// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SantiagoConectaIA.DAL.Models
{
    public partial class spGetOficinasResult
    {
        public bool? bResult { get; set; }
        [StringLength(500)]
        public string vchMessage { get; set; }
        public int? iIdOficina { get; set; }
        [StringLength(250)]
        public string vchNombre { get; set; }
        [StringLength(500)]
        public string vchDireccion { get; set; }
        [StringLength(50)]
        public string vchTelefono { get; set; }
        [StringLength(150)]
        public string vchEmail { get; set; }
        [StringLength(250)]
        public string vchHorario { get; set; }
        public double? flLatitud { get; set; }
        public double? flLongitud { get; set; }
        [StringLength(2147483647)]
        public string vchNotas { get; set; }
        public bool? bActivo { get; set; }
        public DateTime? dtFechaCreacion { get; set; }
        [StringLength(255)]
        public string vchUrlDireccion { get; set; }
    }
}
