// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SantiagoConectaIA.DAL.Models
{
    public partial class spGetNoticiasResult
    {
        public int iIdNoticia { get; set; }
        [StringLength(200)]
        public string vchTitulo { get; set; }
        [StringLength(200)]
        public string vchTituloEn { get; set; }
        [StringLength(2147483647)]
        public string nvchContenido { get; set; }
        [StringLength(2147483647)]
        public string nvchContenidoEn { get; set; }
        [StringLength(500)]
        public string vchImagenPortada { get; set; }
        public DateTime dtFechaPublicacion { get; set; }
        public bool bActivo { get; set; }
        public int? iIdNoticiaImagen { get; set; }
        [StringLength(500)]
        public string vchUrlImagen { get; set; }
    }
}
