// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SantiagoConectaIA.DAL.Models
{
    public partial class spGetAbonoApartadoResult
    {
        public bool? bResult { get; set; }
        [StringLength(500)]
        public string vchMessage { get; set; }
        public int? iIdAbonoApartado { get; set; }
        public int? iIdApartado { get; set; }
        [Column("mAbono", TypeName = "money")]
        public decimal? mAbono { get; set; }
        public DateTime? dtFechaAbono { get; set; }
    }
}
