// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SantiagoConectaIA.DAL.Models
{
    public partial class spGetTramiteDetalleResult
    {
        public bool? bResult { get; set; }
        [StringLength(500)]
        public string vchMessage { get; set; }
        public int? iIdTramite { get; set; }
        [StringLength(250)]
        public string vchNombre { get; set; }
        [StringLength(2147483647)]
        public string nvchDescripcion { get; set; }
        public int? iIdCategoria { get; set; }
        public bool? bModalidadEnLinea { get; set; }
        [Column("mCosto", TypeName = "money")]
        public decimal? mCosto { get; set; }
        public int? iIdOficina { get; set; }
        [StringLength(250)]
        public string vchNombreOficina { get; set; }
        [StringLength(500)]
        public string vchDireccionOficina { get; set; }
        [StringLength(50)]
        public string vchTelefonoOficina { get; set; }
        [StringLength(150)]
        public string vchEmailOficina { get; set; }
        [StringLength(250)]
        public string vchHorarioOficina { get; set; }
        public double? flLatitud { get; set; }
        public double? flLongitud { get; set; }
        [StringLength(2147483647)]
        public string jsnRequisitos { get; set; }
        [StringLength(2147483647)]
        public string jsnPasos { get; set; }
        [StringLength(2147483647)]
        public string jsnDocumentos { get; set; }
    }
}
