// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SantiagoConectaIA.DAL.Models
{
    public partial class spGetTramitesResult
    {
        public bool? bResult { get; set; }
        [StringLength(500)]
        public string vchMessage { get; set; }
        public int? iIdTramite { get; set; }
        [StringLength(250)]
        public string vchNombre { get; set; }
        [StringLength(2147483647)]
        public string nvchDescripcion { get; set; }
        [StringLength(250)]
        public string vchNombreEn { get; set; }
        [StringLength(2147483647)]
        public string nvchDescripcionEn { get; set; }
        public int? iIdCategoria { get; set; }
        public bool? bModalidadEnLinea { get; set; }
        [Column("mCosto", TypeName = "money")]
        public decimal? mCosto { get; set; }
        public int? iIdOficina { get; set; }
        public DateTime? dtFechaCreacion { get; set; }
        public DateTime? dtFechaActualizacion { get; set; }
        public bool? bActivo { get; set; }
    }
}
