// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SantiagoConectaIA.DAL.Models
{
    public partial class spGetPasosPorTramiteResult
    {
        public bool? bResult { get; set; }
        [StringLength(500)]
        public string vchMessage { get; set; }
        public int? iIdTramitePaso { get; set; }
        public int? iIdTramite { get; set; }
        public short? iOrden { get; set; }
        [StringLength(1000)]
        public string nvchDescripcion { get; set; }
        public bool? bActivo { get; set; }
    }
}
