// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SantiagoConectaIA.DAL.Models
{
    public partial class spGetUsuarioResult
    {
        public bool? bResult { get; set; }
        [StringLength(500)]
        public string vchMessage { get; set; }
        public int? iIdUsuario { get; set; }
        [StringLength(200)]
        public string nvchNombre { get; set; }
        [StringLength(510)]
        public string nvchCorreo { get; set; }
        [StringLength(15)]
        public string vchTelefono { get; set; }
        public DateTime? dtFechaRegistro { get; set; }
        public bool? bActivo { get; set; }
    }
}
