// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SantiagoConectaIA.DAL.Models
{
    public partial class spGetFuncionalidadResult
    {
        public bool? bResult { get; set; }
        [StringLength(500)]
        public string vchMessage { get; set; }
        public int? iIdFuncionalidad { get; set; }
        public int? iIdModulo { get; set; }
        [StringLength(2000)]
        public string nvchDescripcion { get; set; }
        [StringLength(800)]
        public string nvchEntidades { get; set; }
        [StringLength(2000)]
        public string nvchInteracciones { get; set; }
        [StringLength(4000)]
        public string nvchTecnico { get; set; }
        [StringLength(4000)]
        public string nvchConsideraciones { get; set; }
    }
}
