// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SantiagoConectaIA.DAL.Models
{
    public partial class spGetProveedorResult
    {
        public bool? bResult { get; set; }
        [StringLength(500)]
        public string vchMessage { get; set; }
        public int? iIdProveedor { get; set; }
        [StringLength(200)]
        public string nvchNombre { get; set; }
        [StringLength(20)]
        public string vchTelefono { get; set; }
        [StringLength(400)]
        public string nvchDireccion { get; set; }
    }
}
