// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SantiagoConectaIA.DAL.Models
{
    public partial class spGetPlanTrabajoResult
    {
        public bool? bResult { get; set; }
        [StringLength(500)]
        public string vchMessage { get; set; }
        public int? iIdPlanTrabajo { get; set; }
        [StringLength(100)]
        public string vchNombre { get; set; }
        [StringLength(4000)]
        public string nvchDescripcion { get; set; }
        [StringLength(50)]
        public string vchEstatus { get; set; }
    }
}
