// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SantiagoConectaIA.DAL.Models
{
    public partial class spGetPedidoResult
    {
        public bool? bResult { get; set; }
        [StringLength(500)]
        public string vchMessage { get; set; }
        public int? iIdPedido { get; set; }
        public int? iIdProveedor { get; set; }
        public DateTime? dtFecha { get; set; }
        [StringLength(4000)]
        public string nvchDescripcion { get; set; }
        [Column("mEnvio", TypeName = "money")]
        public decimal? mEnvio { get; set; }
        [StringLength(200)]
        public string nvchNombre { get; set; }
    }
}
