// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SantiagoConectaIA.DAL.Models
{
    public partial class spGetModuloResult
    {
        public bool? bResult { get; set; }
        [StringLength(500)]
        public string vchMessage { get; set; }
        public int? iIdModulo { get; set; }
        public int? iIdPlanTrabajo { get; set; }
        [StringLength(100)]
        public string vchTitulo { get; set; }
        [StringLength(2000)]
        public string nvchProposito { get; set; }
    }
}
