// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SantiagoConectaIA.DAL.Models
{
    public partial class spGetChatResult
    {
        public bool? bResult { get; set; }
        [StringLength(500)]
        public string vchMessage { get; set; }
        public int? iIdChat { get; set; }
        public int? iIdProyecto { get; set; }
        public DateTime? dtFechaCreacion { get; set; }
        [StringLength(100)]
        public string nvchNombre { get; set; }
        public bool? bActivo { get; set; }
        [StringLength(100)]
        public string nvchThreadId { get; set; }
    }
}
