// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SantiagoConectaIA.DAL.Models
{
    public partial class spGetMensajeResult
    {
        public bool? bResult { get; set; }
        [StringLength(500)]
        public string vchMessage { get; set; }
        public int? iIdMensaje { get; set; }
        public int? iIdChat { get; set; }
        public int? iOrden { get; set; }
        public int? iIdFase { get; set; }
        [StringLength(40)]
        public string nvchRol { get; set; }
        [StringLength(2147483647)]
        public string nvchContenido { get; set; }
        public DateTime? dtFecha { get; set; }
    }
}
