// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SantiagoConectaIA.DAL.Models
{
    public partial class spGetApartadoResult
    {
        public bool? bResult { get; set; }
        [StringLength(500)]
        public string vchMessage { get; set; }
        public int? iIdApartado { get; set; }
        [StringLength(400)]
        public string nvchNombreCliente { get; set; }
        public DateTime? dtFechaApartado { get; set; }
        [Column("mTotal", TypeName = "money")]
        public decimal? mTotal { get; set; }
        [Column("mSubTotal", TypeName = "money")]
        public decimal? mSubTotal { get; set; }
        public bool? bPagado { get; set; }
        [StringLength(2000)]
        public string nvchComentario { get; set; }
        public int? iIdApartadoDetalle { get; set; }
        public int? iIdArticulo { get; set; }
        public int? iCantidad { get; set; }
        [Column("mPrecioFinal", TypeName = "money")]
        public decimal? mPrecioFinal { get; set; }
    }
}
