// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SantiagoConectaIA.DAL.Models
{
    public partial class spGetPasoResult
    {
        public bool? bResult { get; set; }
        [StringLength(500)]
        public string vchMessage { get; set; }
        public int? iIdPaso { get; set; }
        public int? iIdFase { get; set; }
        public short? smNumeroSecuencia { get; set; }
        [StringLength(2147483647)]
        public string nvchDescripcion { get; set; }
        [StringLength(2147483647)]
        public string nvchProposito { get; set; }
        [StringLength(2147483647)]
        public string nvchCaracteristicas { get; set; }
        [StringLength(2147483647)]
        public string nvchEnfoque { get; set; }
        public DateTime? dtCreadoEn { get; set; }
        public DateTime? dtActualizadoEn { get; set; }
    }
}
