// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SantiagoConectaIA.DAL.Models
{
    public partial class spGetInventarioResult
    {
        public bool? bResult { get; set; }
        [StringLength(500)]
        public string vchMessage { get; set; }
        public int? iIdInventario { get; set; }
        public int? iIdArticulo { get; set; }
        public short? smCantidad { get; set; }
        [StringLength(200)]
        public string nvchNombreArticulo { get; set; }
        [StringLength(50)]
        public string vchCodigo { get; set; }
        [StringLength(1000)]
        public string nvchDescripcion { get; set; }
        [Column("mPrecioCompra", TypeName = "money")]
        public decimal? mPrecioCompra { get; set; }
        [Column("mPrecioVenta", TypeName = "money")]
        public decimal? mPrecioVenta { get; set; }
        public int? iIdProveedor { get; set; }
        [StringLength(200)]
        public string nvchNombreProveedor { get; set; }
        [StringLength(20)]
        public string vchTelefono { get; set; }
        [StringLength(400)]
        public string nvchDireccion { get; set; }
    }
}
