// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SantiagoConectaIA.DAL.Models
{
    public partial class spGetTramitesCardResult
    {
        public bool? bResult { get; set; }
        [StringLength(500)]
        public string vchMessage { get; set; }
        public int? iIdTramite { get; set; }
        public int? iIdOficina { get; set; }
        [StringLength(200)]
        public string vchNombreTramite { get; set; }
        [StringLength(2147483647)]
        public string vchDescripcionTramite { get; set; }
        [StringLength(200)]
        public string vchNombreTramiteEn { get; set; }
        [StringLength(2147483647)]
        public string vchDescripcionTramiteEn { get; set; }
        [StringLength(200)]
        public string vchNombreOficina { get; set; }
        [StringLength(500)]
        public string vchDireccionOficina { get; set; }
        [StringLength(50)]
        public string vchTelefonoOficina { get; set; }
        public bool? bModalidadEnLinea { get; set; }
        [Column("dCosto", TypeName = "decimal(18,2)")]
        public decimal? dCosto { get; set; }
        [StringLength(50)]
        public string vchHorarioOficina { get; set; }
    }
}
