// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SantiagoConectaIA.DAL.Models
{
    public partial class spSaveNoticiaImagenResult
    {
        public int bResult { get; set; }
        [StringLength(15)]
        public string vchMessage { get; set; }
    }
}
