// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SantiagoConectaIA.DAL.Models
{
    public partial class spSaveNoticiaResult
    {
        public bool? bResult { get; set; }
        [StringLength(255)]
        public string vchMessage { get; set; }
        public int? iIdNoticia { get; set; }
    }
}
