// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SantiagoConectaIA.DAL.Models
{
    public partial class spSearchRequisitosForChatResult
    {
        public bool? bResult { get; set; }
        [StringLength(500)]
        public string vchMessage { get; set; }
        [StringLength(50)]
        public string vchTipo { get; set; }
        [StringLength(250)]
        public string vchNombre { get; set; }
        [StringLength(2000)]
        public string nvchDetalle { get; set; }
        public bool? bObligatorio { get; set; }
    }
}
