// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SantiagoConectaIA.DAL.Models;

public partial class TestTable
{
    public int IIdTestTable { get; set; }

    public string VchName { get; set; }

    public string VchEmail { get; set; }

    public DateTime DtRegistered { get; set; }
}