// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SantiagoConectaIA.DAL.Models;

public partial class TipoDato
{
    public int IIdTipoDato { get; set; }

    public string NvchTipo { get; set; }

    public string NcvhDescripcion { get; set; }
}