// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SantiagoConectaIA.DAL.Models;

public partial class TramitePaso
{
    public int IIdTramitePaso { get; set; }

    public int IIdTramite { get; set; }

    public short IOrden { get; set; }

    public string NvchDescripcion { get; set; }

    public bool BActivo { get; set; }

    public virtual Tramite IIdTramiteNavigation { get; set; }
}