// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SantiagoConectaIA.DAL.Models;

public partial class Tramite
{
    public int IIdTramite { get; set; }

    public string VchNombre { get; set; }

    public string NvchDescripcion { get; set; }

    public int IIdCategoria { get; set; }

    public bool BModalidadEnLinea { get; set; }

    public decimal MCosto { get; set; }

    public int? IIdOficina { get; set; }

    public DateTime DtFechaCreacion { get; set; }

    public DateTime? DtFechaActualizacion { get; set; }

    public bool BActivo { get; set; }

    public bool BPrecioCalculado { get; set; }

    public string VchNombreEn { get; set; }

    public string NvchDescripcionEn { get; set; }

    public virtual ICollection<Documento> Documentos { get; set; } = new List<Documento>();

    public virtual ICollection<OficinaTramite> OficinaTramites { get; set; } = new List<OficinaTramite>();

    public virtual ICollection<Requisito> Requisitos { get; set; } = new List<Requisito>();

    public virtual ICollection<TramitePaso> TramitePasos { get; set; } = new List<TramitePaso>();
}