// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SantiagoConectaIA.DAL.Models;

public partial class Usuario
{
    public int IIdUsuario { get; set; }

    public string NvchNombre { get; set; }

    public string NvchCorreo { get; set; }

    public string NvchPassword { get; set; }

    public string VchTelefono { get; set; }

    public DateTime DtFechaRegistro { get; set; }

    public bool BActivo { get; set; }
}